### PR TITLE
Sort event by time

### LINKED ISSUE #94: Implement a “sort” command to sort events by date-time

### PR DESCRIPTION
**Pull request by glenn-chew**
Changed eventTime from String to a LocalDateTime class.
The program is now able to sort the events from the earliest event time, to the latest.

Fixes #94

### CODE REVIEW

**Comment by MatchaRRR** [comment]
I think this is a good code implementation and this can be merged.

**Comment by MatchaRRR** [comment]
I think it's a good code implementation but there are some conflicts that need to be solved.

**Review by jemehgoh — COMMENTED** [review]
Looks good mostly, just some nits.

**Review by jemehgoh — APPROVED** [review]
Looks good to merge!

**Pull request merged**
